-- Typed models for the MagicTheGathering SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Card
---@field artist? string
---@field cmc? number
---@field colorIdentity? table
---@field colors? table
---@field flavor? string
---@field id? string
---@field imageUrl? string
---@field legalities? table
---@field loyalty? string
---@field manaCost? string
---@field multiverseid? string
---@field name? string
---@field number? string
---@field originalText? string
---@field originalType? string
---@field power? string
---@field printings? table
---@field rarity? string
---@field rulings? table
---@field set? string
---@field setName? string
---@field subtypes? table
---@field supertypes? table
---@field text? string
---@field toughness? string
---@field type? string
---@field types? table

---@class CardLoadMatch
---@field id string

---@class CardListMatch
---@field artist? string
---@field cmc? number
---@field colorIdentity? table
---@field colors? table
---@field flavor? string
---@field id? string
---@field imageUrl? string
---@field legalities? table
---@field loyalty? string
---@field manaCost? string
---@field multiverseid? string
---@field name? string
---@field number? string
---@field originalText? string
---@field originalType? string
---@field power? string
---@field printings? table
---@field rarity? string
---@field rulings? table
---@field set? string
---@field setName? string
---@field subtypes? table
---@field supertypes? table
---@field text? string
---@field toughness? string
---@field type? string
---@field types? table

---@class Set
---@field block? string
---@field booster? table
---@field border? string
---@field code? string
---@field name? string
---@field onlineOnly? boolean
---@field releaseDate? string
---@field type? string

---@class SetListMatch
---@field block? string
---@field booster? table
---@field border? string
---@field code? string
---@field name? string
---@field onlineOnly? boolean
---@field releaseDate? string
---@field type? string

local M = {}

return M
